### ISSUE TITLE
Assignment 8

### ISSUE THREAD

**Issue by mjzahn** [mjzahn/Assignment-8#1]
I created a presentation in RMarkdown that summarizes some things about me and what I learned from the course this quarter. Thanks for a great course - I learned a ton!

**Comment by mdscheuerell** [comment]
Well done, Marie. Fun fact: I was also born in Milwaukee!

And I'm glad you enjoyed the course.

**Comment by mjzahn** [comment]
No way! I had no idea you were also born in Milwaukee :)
